#!/bin/bash
#--------------------------------------------------
# kcm K8S Cluster Management
# 这个脚步主用于离线安装 K8S集群
#--------------------------------------------------


#--------------------------------------------------
# Shell 脚本基础配置
# 异常处理方式
#--------------------------------------------------
set -o nounset
set -o errexit

# -------------------------------
# KCM 应用程序默认参数
# -------------------------------
# 集群所在的区域，默认 CN
REGISTRY_MIRROR_REGION=CN
DOCKER_VERSION=20.10.8

#打印日志信息方法
function logger() {
  TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
  case "$1" in
    debug)
      echo -e "$TIMESTAMP \033[36mDEBUG\033[0m $2"
      ;;
    info)
      echo -e "$TIMESTAMP \033[32mINFO\033[0m $2"
      ;;
    warn)
      echo -e "$TIMESTAMP \033[33mWARN\033[0m $2"
      ;;
    error)
      echo -e "$TIMESTAMP \033[31mERROR\033[0m $2"
      ;;
    *)
      ;;
  esac
}

### 脚本入口 ##################################################
function main() {
  # 工作空间，依赖程序，配置存储路径
  WORK_SPACE="/etc/kcm"
  echo "Hello World"
  # Bash Shell 验证
  readlink /proc/$$/exe|grep -q "dash" && { logger error "Please use bash shell, not sh"; exit 1; }
  # 执行脚本用户权限验证
  [[ "$EUID" -ne 0 ]] && { logger error "Please run the script by root or the use has root permission"; exit 1; }
  # 执行参数验证
  [[ "$#" -eq 0 ]] && { usage >&2; exit 1; }

  # 检查 'ansible' 是否安装
  which ansible > /dev/null 2>&1 || { logger error "KCM Application need 'Ansible', please install it by pip before run the script..."; usage; exit 1; }

  echo "Hello World"
  case "$1" in
    (download)
      [ "$#" -ge 3 ] || { usage >&2; exit 2; }
      download_packages_images "${@:2}"
      ;;
    (config)
      [ "$#" -ge 3 ] || { usage >&2; exit 2; }
      config_cluster "${@:2}"
      ;;
    (setup)
      [ "$#" -ge 3 ] || { usage-setup >&2; exit 2; }
      setup_cluster "${@:2}"
      ;;
  esac
}